/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as Root_layoutRouteImport } from './routes/_root_layout'
import { Route as SplatRouteImport } from './routes/$'
import { Route as Root_layoutIndexRouteImport } from './routes/_root_layout/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const Root_layoutRoute = Root_layoutRouteImport.update({
  id: '/_root_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Root_layoutIndexRoute = Root_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Root_layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/health': typeof HealthRoute
  '/': typeof Root_layoutIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/health': typeof HealthRoute
  '/': typeof Root_layoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_root_layout': typeof Root_layoutRouteWithChildren
  '/health': typeof HealthRoute
  '/_root_layout/': typeof Root_layoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/health' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/health' | '/'
  id: '__root__' | '/$' | '/_root_layout' | '/health' | '/_root_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  Root_layoutRoute: typeof Root_layoutRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root_layout': {
      id: '/_root_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Root_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root_layout/': {
      id: '/_root_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Root_layoutIndexRouteImport
      parentRoute: typeof Root_layoutRoute
    }
  }
}

interface Root_layoutRouteChildren {
  Root_layoutIndexRoute: typeof Root_layoutIndexRoute
}

const Root_layoutRouteChildren: Root_layoutRouteChildren = {
  Root_layoutIndexRoute: Root_layoutIndexRoute,
}

const Root_layoutRouteWithChildren = Root_layoutRoute._addFileChildren(
  Root_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  Root_layoutRoute: Root_layoutRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
